version: '3'

services:

  asteroid-api-1:
    container_name: asteroid-api-1
    build:
      context: ..
      dockerfile: ./Asteroids.API/Dockerfile
    environment:
      SIGNALRHUB: "http://asteroid-signalr:8082/asteroidHub"
      ACTORSYSTEM: "asteroids-actor-system"
      CLUSTER_PORT: "8081"
      CLUSTER_IP: "asteroid-api-1"
      CLUSTER_SEED: "asteroid-api-1:8081"
      CLUSTER_ROLES: "lobby, signalR"     
    ports:
      - 1994:8081
      - 1995:8080
    depends_on:
      - asteroid-signalr

  asteroid-api-2:
    container_name: asteroid-api-2
    build:
      context: ..
      dockerfile: ./Asteroids.API/Dockerfile
    environment:
      SIGNALRHUB: "http://asteroid-signalr:8082/asteroidHub"
      ACTORSYSTEM: "asteroids-actor-system"
      CLUSTER_PORT: "8081"
      CLUSTER_IP: "asteroid-api-2"
      CLUSTER_SEED: "asteroid-api-1:8081"
      CLUSTER_ROLES: "lobby, signalR"     
    ports:
      - 1996:8081
      - 1997:8080
    depends_on:
      - asteroid-signalr

  asteroid-api-3:
    container_name: asteroid-api-3
    build:
      context: ..
      dockerfile: ./Asteroids.API/Dockerfile
    environment:
      SIGNALRHUB: "http://asteroid-signalr:8082/asteroidHub"
      ACTORSYSTEM: "asteroids-actor-system"
      CLUSTER_PORT: "8081"
      CLUSTER_IP: "asteroid-api-3"
      CLUSTER_SEED: "asteroid-api-1:8081"
      CLUSTER_ROLES: "lobby, signalR"     
    ports:
      - 1998:8081
      - 1999:8080
    depends_on:
      - asteroid-signalr

  asteroid-signalr:
    container_name: asteroid-signalr
    build:
      context: ..
      dockerfile: ./Asteroids.SignalR/Dockerfile
    ports:
      - 2000:8082

  asteroid-web-1:
    container_name: asteroid-web-1
    build:
      context: ..
      dockerfile: ./Asteroids.Web/Dockerfile
      args:
        SIGNALR_HUB_URL_ARG: "http://api.localhost/asteroidHub"
    ports:
      - 2001:80

  nginx:
    image: nginx:latest
    container_name: jz-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - nginx_cache_data:/var/cache/nginx
    ports:
      - 80:80
    restart: unless-stopped
